### ISSUE TITLE
Can I use more than one alternate toolbar?

### ISSUE THREAD

**Issue by ditorahard** [davideanderson/medium-editor-toolbar-states#1]
Hey, thank you for making this. This stuff is really cool and I'm now experimenting with it. 

My question is, can I use this for more than one alternate toolbar? For example, I want to use alternate toolbar 1 when the text is italic and I want to use alternate toolbar 2 when the text is bold.

**Comment by ditorahard** [comment]
Nevermind, I solved the issue myself by using getStateNameforNode. I guess I am a little bit confused because this plugin doesn't have any documentation yet. 

Thanks anyway for making this plugin!

**Comment by davideanderson** [comment]
Definitely.  In my project, I actually have a lot of alternate toolbars, based on what is selected.

Using this configuration, you simply have to add an html attribute named 'toolbar-state' somewhere between the selected text up to the medium editor itself.  Then set the value of the 'toolbar-state' attribute to the particular state you want to display ('default', 'image', etc.).

```
            'medium-editor-toolbar-states': new window.MediumEditorToolbarStates({
                states: {
                    default: {
                        buttons: ['bold', 'italic', 'underline', 'h2', 'h3', 'quote',
                            'unorderedList', 'orderedList', 'anchor']
                    },
                    image: {
                        buttons: ['alignLeft', 'alignCenter', 'alignRight', 'crop', 'delete']
                    },
                    video: {
                        buttons: ['alignLeft', 'alignCenter', 'alignRight', 'delete']
                    },
                    crop: {
                        buttons: ['crop', 'save', 'cancel']
                    },
                    caption: {
                        buttons: ['bold', 'italic', 'underline', 'anchor']
                    },
                    attachedFile: {
                        buttons: ['delete']
                    },
                    uploading: {
                        buttons: ['cancelUpload']
                    }
                },
                attributeName: 'toolbar-state'
            })
```
